DROP TABLE IF EXISTS LOCALE;
DROP TABLE IF EXISTS DRIVER;

CREATE TABLE DRIVER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(250) NOT NULL,
    AGE VARCHAR(250) NOT NULL,
    GENDER INT NOT NULL,
    HAS_OWN_TRUCK BOOLEAN NOT NULL,
    TRUCK_TYPE INT NOT NULL,
    CREATION_DATE VARCHAR(250),
    LAST_UPDATE_DATE VARCHAR(250)
);

INSERT INTO DRIVER (NAME, AGE, GENDER, HAS_OWN_TRUCK, TRUCK_TYPE, CREATION_DATE, LAST_UPDATE_DATE) VALUES
('daniel', '22', 0, true, 2, '10/10/2020', '10/10/2020');

CREATE TABLE LOCALE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    DRIVER_ID INT NOT NULL,
    LOCALE_TYPE INT NOT NULL,
    LONGITUDE INT NOT NULL,
    LATITUDE INT NOT NULL
);

ALTER TABLE LOCALE
ADD FOREIGN KEY (DRIVER_ID)
REFERENCES DRIVER(ID);

INSERT INTO LOCALE (DRIVER_ID, LOCALE_TYPE, LONGITUDE, LATITUDE) VALUES
(1, 0, 101010, 121212),
(1, 1, 202020, 212121);